[phases.setup]
nixPkgs = ["python312", "pip", "libGL", "libGLU", "mesa", "glib", "gtk3", "xorg.libX11", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmd = "python yolo_server.py"
